safe:        false
auto:        false
server:      false

source:      ./_source
destination: ./public
plugins:     ./_source/_plugins

title : Algo Class
tagline: learning and visualizing algorithms
author :
  name : André M. Ribeiro dos Santos
  email : andremrsantos@gmail.com
  github : andremrsantos
  twitter : andremrsantos
  gravatar: andremrsantos@gmail.com

comments :
  disqus :
    short_name : jekyllbootstrap

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

paginate:	 10

exclude: 	[".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile"]

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

assets:
  compress:
    css:  sass
    js:   uglifier
